[build-system]

requires=["setuptools"]
build-backend="setuptools.build_meta"

[project]

name="gizmo"
version="0.0.1"
description="UI items"
dependencies=[
	"pynvim==0.4.3",
	"PyQt6==5.15.9",
	"PyQtWebEngine==5.15.6",
	]

[tools.setuptools.package-data]

"*"=["*"]

[tools.setuptools.packages.find]

where=["src"]
