[build-system]

requires=["setuptools"]
build-backend="setuptools.build_meta"

[project]

name="qapp"
version="0.0.1"
description="Vim-like application building framework in PyQt"
dependencies=[
	"plug==0.0.1",
	"pynvim==0.4.3",
	"pynput==1.7.6",
	"PyQt5==5.15.9",
	"PyQtWebEngine==5.15.6",
	]

[tools.setuptools.package-data]

"*"=["*"]

[tools.setuptools.packages.find]

where=["src"]
