[tool.poetry]
name = "gizmo"
version = "0.0.1"
description = "Qt UI tool"
authors = ["AO <adhambek.otabekov.post@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8"
pynvim = ">=0.4.3"
PyQt6  = ">=6.5.1"
PyQt6-WebEngine = ">=6.5.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
